# Generated by Django 4.2.5 on 2023-09-21 09:17

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('rarity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('effect', models.TextField()),
                ('image_dir', models.URLField(validators=[django.core.validators.URLValidator(), main.models.validate_image_url])),
            ],
        ),
    ]
