# Generated by Django 4.2.5 on 2023-09-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='effect',
            field=models.TextField(default='This is a description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.TextField(default='★'),
            preserve_default=False,
        ),
    ]
