# Generated by Django 4.2.5 on 2023-09-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_effect_item_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
