# Generated by Django 4.2.5 on 2023-09-13 15:10

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_dir',
            field=models.URLField(validators=[django.core.validators.URLValidator(), main.models.validate_image_url]),
        ),
    ]
